# Generated by Django 4.1.7 on 2023-03-15 07:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Поля автоматический заполняется!', null=True)),
                ('image', models.ImageField(upload_to='media/photo/%Y/%m/%d')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Glav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='NameCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField()),
                ('full_text', ckeditor.fields.RichTextField()),
                ('id_glav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.glav')),
            ],
        ),
        migrations.CreateModel(
            name='Raz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('categori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.namecategories')),
            ],
        ),
        migrations.AddField(
            model_name='glav',
            name='razdel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.raz'),
        ),
    ]
