# Generated by Django 4.1.7 on 2023-03-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glav',
            name='slug',
            field=models.SlugField(blank=True, help_text='Поля автоматический заполняется!', null=True),
        ),
        migrations.AddField(
            model_name='namecategories',
            name='slug',
            field=models.SlugField(blank=True, help_text='Поля автоматический заполняется!', null=True),
        ),
        migrations.AddField(
            model_name='raz',
            name='slug',
            field=models.SlugField(blank=True, help_text='Поля автоматический заполняется!', null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='slug',
            field=models.SlugField(blank=True, help_text='Поля автоматический заполняется!', null=True),
        ),
    ]
