# Generated by Django 4.1.7 on 2023-03-15 07:37

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0002_glav_slug_namecategories_slug_raz_slug_theme_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', ckeditor.fields.RichTextField()),
                ('img', models.ImageField(upload_to='media/photo/%Y/%m/%d')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
