# Generated by Django 4.1.7 on 2023-03-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/photo/%Y/%m/%d')),
                ('fio', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Поля автоматический заполняется!')),
                ('special', models.CharField(max_length=255)),
                ('phone', models.IntegerField(max_length=10)),
                ('rezume', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
