# Generated by Django 4.1.7 on 2023-03-22 09:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0005_alter_about_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='glav',
            options={'verbose_name': 'Глава', 'verbose_name_plural': 'Глава раздела'},
        ),
        migrations.AlterModelOptions(
            name='namecategories',
            options={'verbose_name': 'Предмет ', 'verbose_name_plural': 'Предметы категории'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='raz',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Раздел предмета'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Тема главы'},
        ),
        migrations.AlterField(
            model_name='about',
            name='fio',
            field=models.CharField(max_length=255, verbose_name='Фамилия, Имя, Отечества'),
        ),
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(upload_to='media/photo/%Y/%m/%d', verbose_name='изображение работника'),
        ),
        migrations.AlterField(
            model_name='about',
            name='rezume',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d', verbose_name='резюме необезательно'),
        ),
        migrations.AlterField(
            model_name='about',
            name='special',
            field=models.CharField(max_length=255, verbose_name='специалисть'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='count',
            field=models.IntegerField(verbose_name='номер категории'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(upload_to='media/photo/%Y/%m/%d', verbose_name='изображение категории'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='glav',
            name='name',
            field=models.CharField(max_length=250, verbose_name='глава раздела'),
        ),
        migrations.AlterField(
            model_name='glav',
            name='razdel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.raz', verbose_name='Из какого раздела'),
        ),
        migrations.AlterField(
            model_name='namecategories',
            name='id_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.categories', verbose_name='Из какого категории'),
        ),
        migrations.AlterField(
            model_name='namecategories',
            name='title',
            field=models.CharField(max_length=100, verbose_name='название предмета'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="дата новость 'автоматически заполняется'"),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(upload_to='media/photo/%Y/%m/%d', verbose_name='изображение новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст:'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название новости'),
        ),
        migrations.AlterField(
            model_name='raz',
            name='categori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.namecategories', verbose_name='Из какого предмета'),
        ),
        migrations.AlterField(
            model_name='raz',
            name='name',
            field=models.CharField(max_length=250, verbose_name='раздел предмета'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='full_text',
            field=ckeditor.fields.RichTextField(verbose_name='Тексе:'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='id_glav',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_base.glav', verbose_name='Из какого глава'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme',
            field=models.TextField(verbose_name='Тема:'),
        ),
    ]
