# Generated by Django 4.1.7 on 2023-03-22 11:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userregister', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='telInfo',
        ),
        migrations.AddField(
            model_name='datauser',
            name='password',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datauser',
            name='telInfo',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
